server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:32768/marketplace"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

logging:
  level:
    root: info

default:
  page:
    size: 20
  role: MANAGER

