server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/v1/companies/**
        - id: user-transaction-service
          uri: lb://user-transaction-service
          predicates:
            - Path=/api/v1/users/transactions, /api/v1/users/{segment}/transactions
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: position-service
          uri: lb://position-service
          predicates:
            - Path=/api/v1/items/**, /api/v1/categories/**, /api/v1/positions/**
  config:
    import: "optional:configserver:${CONFIG_URI:http://localhost:8888}"

eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"