server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: app
  datasource:
    url: "jdbc:postgresql://localhost:32768/marketplace"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          batch_size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/marketplace

idm:
  realm-name: "marketplace"
  server-url: "http://localhost:8079"
  client-id: "idm-client"
  client-secret: "xRKE2WYIcZr5KhYyy7JeGSLCTIn7Y0BX"
  admin-username: "idm-admin"
  admin-password: "admin"
  pool-size: 10

logging:
  level:
    root: info
    com.modsensoftware.marketplace: debug

default:
  page:
    size: 20
  role: MANAGER
  role-prefix: ROLE_
  jwt-realm-access-claim: realm_access
  jwt-roles-claim: roles

exception:
  message:
    categoryNotFound: "Category entity with id=%s is not present."
    companyNotFound: "Company entity with id=%s is not present."
    itemNotFound: "Item entity with uuid=%s is not present."
    positionNotFound: "Position entity with id=%s is not found."
    userNotFound: "User entity with uuid=%s is not found."
    invalidCreatedBetweenFilter: "Filter 'created' = %s is invalid"
    companyEmailTaken: "Company with email %s already exists"
    nonUniqueUser: "User with such email %s or such username %s already exists"
    itemVersionsMismatch: "Provided item version does not match with the one in the database"
    positionVersionsMismatch: "Provided position version does not match with the one in the database"
    sessionFactoryInitFail: "Initialization of SessionFactory failed"
    noItemVersionProvided: "No version for item with id %s was provided"
    noPositionVersionProvided: "No version for position with id %s was provided"
    insufficientItemsInStock: "Not enough items in stock for position with id=%s. Wanted amount=%s. Currently in stock=%s"
    insufficientOrderAmount: "Wanted amount=%s is less than position's(id=%s) minimum amount=%s"
    invalidCredentialsException: "Provided credentials are incorrect"
    userPasswordAbsent: "Could not update user as password is not present."
