server:
  port: 8080

spring:
  application:
    name: app
  datasource:
    url: "jdbc:postgresql://localhost:32768/marketplace"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          batch_size: 5
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    loadbalancer:
      cache:
        caffeine:
          spec: maximumSize=10,initialCapacity=50,expireAfterAccess=300