server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: app
  datasource:
    url: "jdbc:postgresql://localhost:32768/marketplace"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          batch_size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/marketplace
  config:
    import: optional:configserver:http://localhost:8888

idm:
  realm-name: "marketplace"
  server-url: "http://localhost:8079"
  client-id: "idm-client"
  client-secret: "xRKE2WYIcZr5KhYyy7JeGSLCTIn7Y0BX"
  admin-username: "idm-admin"
  admin-password: "admin"
  pool-size: 10
