version: "3.8"

services:
  modsen-marketplace-postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    volumes:
      - marketplace-postgres-data:/var/lib/postgresql/data
    ports:
      - "32768:5432"
  keycloak:
    container_name: modsen-marketplace-keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 32768
      DB_DATABASE: marketplace
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8079:8080"
    depends_on:
      - modsen-marketplace-postgres
    command:
      - start-dev

volumes:
  marketplace-postgres-data:
    driver: local
