version: "3.9"

services:
  modsen-marketplace-postgres:
    container_name: modsen-marketplace-postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    volumes:
      - marketplace-postgres-data:/var/lib/postgresql/data
    ports:
      - "32768:5432"

  keycloak:
    container_name: modsen-marketplace-keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 32768
      DB_DATABASE: marketplace
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    depends_on:
      - modsen-marketplace-postgres
    command:
      - start-dev

  config-service:
    image: marketplace-config-service:latest
    ports:
      - "8888:8888"

  eureka-service:
    image: marketplace-discovery-service:latest
    environment:
      CONFIG_URI: http://config-service:8888
    ports:
      - "8761:8761"
    depends_on:
      - config-service

  company-service:
    image: marketplace-company-service:latest
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-service:8761/eureka
      POSTGRES_ADDRESS: modsen-marketplace-postgres:5432
      KEYCLOAK_URI: http://keycloak:8080
    ports:
      - "8090:8090"
    depends_on:
      - config-service
      - eureka-service
      - modsen-marketplace-postgres
      - keycloak

  app:
    image: marketplace-app:latest
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-service:8761/eureka
      POSTGRES_ADDRESS: modsen-marketplace-postgres:5432
      KEYCLOAK_URI: http://keycloak:8080
    ports:
      - "8085:8085"
    depends_on:
      - config-service
      - eureka-service
      - company-service
      - modsen-marketplace-postgres
      - keycloak

  user-transaction-service:
    image: marketplace-user-transaction-service:latest
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-service:8761/eureka
      POSTGRES_ADDRESS: modsen-marketplace-postgres:5432
      KEYCLOAK_URI: http://keycloak:8080
    ports:
      - "8100:8100"
    depends_on:
      - config-service
      - eureka-service
      - modsen-marketplace-postgres
      - app
      - keycloak

  gateway-service:
    image: marketplace-gateway-service:latest
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-service:8761/eureka
    ports:
      - "8000:8000"
    depends_on:
      - config-service
      - eureka-service
      - app
      - company-service
      - user-transaction-service

volumes:
  marketplace-postgres-data:
    driver: local
  keycloak-data:
    driver: local