version: "3.9"

services:
  modsen-marketplace-postgres:
    container_name: modsen-marketplace-postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    volumes:
      - marketplace-postgres-data:/var/lib/postgresql/data
    ports:
      - "32768:5432"

  keycloak:
    container_name: modsen-marketplace-keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 32768
      DB_DATABASE: marketplace
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    depends_on:
      - modsen-marketplace-postgres
    command:
      - start-dev

  mongodb:
    container_name: modsen-marketplace-mongodb
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONDO_INITDB_DATABASE: marketplace_positions
    ports:
      - "27017:27017"

  zookeeper:
    container_name: modsen-marketplace-zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    container_name: modsen-marketplace-kafka
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper

  config-service:
    image: simmissim/marketplace-config-service:latest
    ports:
      - "8888:8888"

  eureka-service:
    image: simmissim/marketplace-discovery-service:latest
    environment:
      CONFIG_URI: http://config-service:8888
    ports:
      - "8761:8761"
    depends_on:
      - config-service

  company-service:
    image: simmissim/marketplace-company-service:latest
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-service:8761/eureka
      POSTGRES_ADDRESS: modsen-marketplace-postgres:5432
      KEYCLOAK_URI: http://keycloak:8080
    ports:
      - "8090:8090"
    depends_on:
      - config-service
      - eureka-service
      - modsen-marketplace-postgres
      - keycloak

  user-service:
    image: simmissim/marketplace-user-service:latest
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-service:8761/eureka
      POSTGRES_ADDRESS: modsen-marketplace-postgres:5432
      KEYCLOAK_URI: http://keycloak:8080
    ports:
      - "8095:8095"
    depends_on:
      - config-service
      - eureka-service
      - modsen-marketplace-postgres
      - keycloak

  position-service:
    image: simmissim/marketplace-position-service:latest
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-service:8761/eureka
      MONGO_ADDRESS: root:root@mongodb:27017
      KEYCLOAK_URI: http://keycloak:8080
      KAFKA_ADDRESS: kafka:9092
    ports:
      - "8085:8085"
    depends_on:
      - config-service
      - eureka-service
      - user-service
      - mongodb
      - keycloak

  user-transaction-service:
    image: simmissim/marketplace-user-transaction-service:latest
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-service:8761/eureka
      POSTGRES_ADDRESS: modsen-marketplace-postgres:5432
      KEYCLOAK_URI: http://keycloak:8080
      KAFKA_ADDRESS: kafka:9092
    ports:
      - "8100:8100"
    depends_on:
      - config-service
      - eureka-service
      - modsen-marketplace-postgres
      - position-service
      - user-service
      - keycloak

  gateway-service:
    image: simmissim/marketplace-gateway-service:latest
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-service:8761/eureka
    ports:
      - "8000:8000"
    depends_on:
      - config-service
      - eureka-service
      - position-service
      - user-service
      - company-service
      - user-transaction-service

volumes:
  marketplace-postgres-data:
    driver: local
  keycloak-data:
    driver: local