server:
  port: 8090

spring:
  application:
    name: company-service
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:32768}/marketplace"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: company_service
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          batch_size: 5
  config:
    import: "optional:configserver:${CONFIG_URI:http://localhost:8888}"

eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
