server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/S1mm1ssim/marketplace-config-repo
          default-label: master
          clone-on-start: true