server:
  port: 8100

spring:
  application:
    name: user-transaction-service
  datasource:
    url: "jdbc:postgresql://${POSTGRES_ADDRESS:localhost:32768}/marketplace"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: user_transaction_service
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          batch_size: 5
  config:
    import: "optional:configserver:${CONFIG_URI:http://localhost:8888}"
  cloud:
    loadbalancer:
      cache:
        caffeine:
          spec: maximumSize=10,initialCapacity=50,expireAfterAccess=300s

eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"